# SPDX-FileCopyrightText: 2026 Tsolo.io
#
# SPDX-License-Identifier: Apache-2.0

---

name: Build
run-name: Build process for CyCAx Parts
on: [push]

jobs:
  build:
    runs-on: "ubuntu-22.04"
    container:
      image: gitea.tu.tsolo.net/tsolo/ubuntu:22-ci
    steps:
      - name: Checkout repository code
        uses: https://gitea.com/actions/checkout@v4
      - name: Install packages
        run: |
          apt-get update
          apt-get install -y libgl-dev
          #- name: Run tests
          #run: hatch run testing:ci
      - name: Package with Python
        run: make build
      - name: Get local version
        run: |
          LOCAL_VERSION=$(hatch version)
          echo "LOCAL_VERSION=$LOCAL_VERSION"
          echo "LOCAL_VERSION=$LOCAL_VERSION" >> $GITHUB_ENV
      - name: Get packaged versions
        run: |
          PACKAGED_VERSIONS=$(pip index versions cycax-parts --pre --index-url https://${{ vars.REGISTRYHOST }}/api/packages/Kuat/pypi/simple/ | tr -d '\n')
          echo "PACKAGED_VERSIONS="$PACKAGED_VERSIONS"
          echo "PACKAGED_VERSIONS="$PACKAGED_VERSIONS" >> $GITHUB_ENV
      - name: Publish Python package
        env:
          HATCH_INDEX_REPO: "https://${{ vars.REGISTRYHOST }}/api/packages/Kuat/pypi"
          HATCH_INDEX_USER: "${{ vars.REGISTRYUSER }}"
          HATCH_INDEX_AUTH: "${{ secrets.REGISTRYPASSWORD }}"
        run: |
          hatch --verbose publish
          pip index versions cycax-parts --pre --index-url https://${{ vars.REGISTRYHOST }}/api/packages/Kuat/pypi/simple/
        if: ${{ !contains(env.PACKAGED_VERSIONS, env.LOCAL_VERSION) }}
